---
- name: Copy dbora
  template: src=dbora.j2 dest=/etc/init.d/dbora

- name: Set oratab
  template: src=oratab.j2 dest=/etc/oratab

- name: Prepare dbora step 1
  command: chmod 750 /etc/init.d/dbora

- name: Prepare dbora step 2
  command: chkconfig --add dbora

- name: Prepare dbora step 3
  command: chkconfig dbora on

- name: Final reboot server
  reboot:
