---
- name: Check  zip in tmp
  stat: path=/tmp/{{ oracle_db_zip }}
  register: zip1_checked
  
- name: Copy DB zip to destination
  copy: src={{ nfs_sd }}/{{ oracle_db_zip }} dest=/tmp/{{ oracle_db_zip }}

- name: Unzip image 1
  unarchive: src=/tmp/{{ oracle_db_zip }} dest=/tmp remote_src=yes
